#!/bin/bash

jupyter labextension install \
                            @jupyter-widgets/jupyterlab-manager \
                            @pyviz/jupyterlab_pyviz
jupyter serverextension enable --py nbgitpuller --sys-prefix

#EOF
